# Kueue queues for torchtitan CUDA/NVIDIA JobSet label:
#   kueue.x-k8s.io/queue-name: torchtitan-cuda

apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default

---

apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: torchtitan-cuda-cq
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory", "ephemeral-storage", "nvidia.com/gpu"]
    flavors:
    - name: default
      resources:
      - name: "cpu"
        nominalQuota: "200"
      - name: "memory"
        nominalQuota: "2Ti"
      - name: "ephemeral-storage"
        nominalQuota: "128Gi"
      - name: "nvidia.com/gpu"
        nominalQuota: "16"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: torchtitan-cuda
  namespace: default
spec:
  clusterQueue: torchtitan-cuda-cq
